### ISSUE TITLE
Unexpected token } on running command sls -v or sls deploy

### ISSUE THREAD

**Issue by Play9win** [serverless-tencent/serverless-tencent-tools#17]
Hi there, 

We saw that this package was updated just an hour ago. We use serverless for deploying our application. The CI was working fine until just now ... we are facing this error continuously:

![image](https://user-images.githubusercontent.com/54166943/78773356-b9679600-79b0-11ea-8c3e-dac721ad91d3.png)

**Comment by RomkaSk** [comment]
Hi!
I have the same problem.
<img width="738" alt="Снимок экрана 2020-04-08 в 13 22 21" src="https://user-images.githubusercontent.com/11800834/78773560-1442c280-799c-11ea-92ac-9a134c179cac.png">

**Comment by IoannMelnychuk** [comment]
I got the same thing

**Comment by anycodes** [comment]
OK, I have updated this package. I am sorry for this error. 
I don't know why the code was incorrectly formatted. I need to further investigate the cause. At present, the previous version has been overwritten and can be used. I'm sorry about this.

https://www.npmjs.com/package/serverless-tencent-tools/v/1.0.14

Now, you could reupdate the serverless-framework.
